//: ### Errores
//: 3) C칩mo hacer que una closure, par치metro de una funci칩n, lance un error.

func calculoCostoso(calculo: () throws -> Void) rethrows {
    try calculo()
}

calculoCostoso {
    print("Realizando c치lculo...")
}

enum ErrorCalculo: Error {
    case error
}

do{
    try calculoCostoso {
        let x = Int.random(in: 1...5)
        if x == 2 {
            throw ErrorCalculo.error
        }
    }
}catch {
    print("Error \(error)")
}




